# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/editor/forms/date.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Date(object):
    def setupUi(self, Date):
        Date.setObjectName("Date")
        Date.resize(475, 202)
        Date.setMinimumSize(QtCore.QSize(475, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Date)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultLayout = QtWidgets.QHBoxLayout()
        self.defaultLayout.setObjectName("defaultLayout")
        self.defaultLabel = QtWidgets.QLabel(Date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultLabel.sizePolicy().hasHeightForWidth())
        self.defaultLabel.setSizePolicy(sizePolicy)
        self.defaultLabel.setObjectName("defaultLabel")
        self.defaultLayout.addWidget(self.defaultLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.defaultLayout.addItem(spacerItem)
        self.defaultField = QtWidgets.QDateEdit(Date)
        self.defaultField.setMinimumSize(QtCore.QSize(200, 0))
        self.defaultField.setCalendarPopup(True)
        self.defaultField.setDate(QtCore.QDate(1752, 9, 14))
        self.defaultField.setObjectName("defaultField")
        self.defaultLayout.addWidget(self.defaultField)
        self.verticalLayout.addLayout(self.defaultLayout)
        self.minValueLayout = QtWidgets.QHBoxLayout()
        self.minValueLayout.setObjectName("minValueLayout")
        self.minValueLabel = QtWidgets.QLabel(Date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minValueLabel.sizePolicy().hasHeightForWidth())
        self.minValueLabel.setSizePolicy(sizePolicy)
        self.minValueLabel.setObjectName("minValueLabel")
        self.minValueLayout.addWidget(self.minValueLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.minValueLayout.addItem(spacerItem1)
        self.minValueField = QtWidgets.QDateEdit(Date)
        self.minValueField.setMinimumSize(QtCore.QSize(200, 0))
        self.minValueField.setCalendarPopup(True)
        self.minValueField.setDate(QtCore.QDate(1752, 9, 14))
        self.minValueField.setObjectName("minValueField")
        self.minValueLayout.addWidget(self.minValueField)
        self.verticalLayout.addLayout(self.minValueLayout)
        self.maxValueLayout = QtWidgets.QHBoxLayout()
        self.maxValueLayout.setObjectName("maxValueLayout")
        self.maxValueLabel = QtWidgets.QLabel(Date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxValueLabel.sizePolicy().hasHeightForWidth())
        self.maxValueLabel.setSizePolicy(sizePolicy)
        self.maxValueLabel.setObjectName("maxValueLabel")
        self.maxValueLayout.addWidget(self.maxValueLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.maxValueLayout.addItem(spacerItem2)
        self.maxValueField = QtWidgets.QDateEdit(Date)
        self.maxValueField.setMinimumSize(QtCore.QSize(200, 0))
        self.maxValueField.setCalendarPopup(True)
        self.maxValueField.setDate(QtCore.QDate(9999, 12, 31))
        self.maxValueField.setObjectName("maxValueField")
        self.maxValueLayout.addWidget(self.maxValueField)
        self.verticalLayout.addLayout(self.maxValueLayout)
        self.increaseButtonsCheckbox = QtWidgets.QRadioButton(Date)
        self.increaseButtonsCheckbox.setChecked(True)
        self.increaseButtonsCheckbox.setObjectName("increaseButtonsCheckbox")
        self.verticalLayout.addWidget(self.increaseButtonsCheckbox)
        self.calendarButtonCheckbox = QtWidgets.QRadioButton(Date)
        self.calendarButtonCheckbox.setChecked(False)
        self.calendarButtonCheckbox.setObjectName("calendarButtonCheckbox")
        self.verticalLayout.addWidget(self.calendarButtonCheckbox)

        self.retranslateUi(Date)
        QtCore.QMetaObject.connectSlotsByName(Date)

    def retranslateUi(self, Date):
        _translate = QtCore.QCoreApplication.translate
        Date.setWindowTitle(_translate("Date", "Date"))
        self.defaultLabel.setText(_translate("Date", "Значение по умолчанию"))
        self.minValueLabel.setText(_translate("Date", "Минимальное значение"))
        self.maxValueLabel.setText(_translate("Date", "Максимальное значение"))
        self.increaseButtonsCheckbox.setText(_translate("Date", "Кнопки увеличения даты"))
        self.calendarButtonCheckbox.setText(_translate("Date", "Кнопка календаря"))
