# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/editor/forms/text.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Text(object):
    def setupUi(self, Text):
        Text.setObjectName("Text")
        Text.resize(475, 126)
        Text.setMinimumSize(QtCore.QSize(475, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Text)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultLayout = QtWidgets.QHBoxLayout()
        self.defaultLayout.setObjectName("defaultLayout")
        self.defaultLabel = QtWidgets.QLabel(Text)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultLabel.sizePolicy().hasHeightForWidth())
        self.defaultLabel.setSizePolicy(sizePolicy)
        self.defaultLabel.setObjectName("defaultLabel")
        self.defaultLayout.addWidget(self.defaultLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.defaultLayout.addItem(spacerItem)
        self.defaultField = QtWidgets.QLineEdit(Text)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultField.sizePolicy().hasHeightForWidth())
        self.defaultField.setSizePolicy(sizePolicy)
        self.defaultField.setMinimumSize(QtCore.QSize(200, 0))
        self.defaultField.setMaximumSize(QtCore.QSize(200, 16777215))
        self.defaultField.setClearButtonEnabled(True)
        self.defaultField.setObjectName("defaultField")
        self.defaultLayout.addWidget(self.defaultField)
        self.verticalLayout.addLayout(self.defaultLayout)
        self.hintLayout = QtWidgets.QHBoxLayout()
        self.hintLayout.setObjectName("hintLayout")
        self.hintLabel = QtWidgets.QLabel(Text)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hintLabel.sizePolicy().hasHeightForWidth())
        self.hintLabel.setSizePolicy(sizePolicy)
        self.hintLabel.setObjectName("hintLabel")
        self.hintLayout.addWidget(self.hintLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hintLayout.addItem(spacerItem1)
        self.hintField = QtWidgets.QLineEdit(Text)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hintField.sizePolicy().hasHeightForWidth())
        self.hintField.setSizePolicy(sizePolicy)
        self.hintField.setMinimumSize(QtCore.QSize(200, 0))
        self.hintField.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hintField.setClearButtonEnabled(True)
        self.hintField.setObjectName("hintField")
        self.hintLayout.addWidget(self.hintField)
        self.verticalLayout.addLayout(self.hintLayout)
        self.clearButtonCheckbox = QtWidgets.QCheckBox(Text)
        self.clearButtonCheckbox.setObjectName("clearButtonCheckbox")
        self.verticalLayout.addWidget(self.clearButtonCheckbox)

        self.retranslateUi(Text)
        QtCore.QMetaObject.connectSlotsByName(Text)

    def retranslateUi(self, Text):
        _translate = QtCore.QCoreApplication.translate
        Text.setWindowTitle(_translate("Text", "Text"))
        self.defaultLabel.setText(_translate("Text", "Значение по умолчанию"))
        self.defaultField.setPlaceholderText(_translate("Text", "Значение по умолчанию"))
        self.hintLabel.setText(_translate("Text", "Подсказка"))
        self.hintField.setPlaceholderText(_translate("Text", "Подсказка"))
        self.clearButtonCheckbox.setText(_translate("Text", "Кнопка очистки поля"))
