# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/editor/forms/time.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Time(object):
    def setupUi(self, Time):
        Time.setObjectName("Time")
        Time.resize(475, 170)
        Time.setMinimumSize(QtCore.QSize(475, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Time)
        self.verticalLayout.setObjectName("verticalLayout")
        self.defaultLayout = QtWidgets.QHBoxLayout()
        self.defaultLayout.setObjectName("defaultLayout")
        self.defaultLabel = QtWidgets.QLabel(Time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultLabel.sizePolicy().hasHeightForWidth())
        self.defaultLabel.setSizePolicy(sizePolicy)
        self.defaultLabel.setObjectName("defaultLabel")
        self.defaultLayout.addWidget(self.defaultLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.defaultLayout.addItem(spacerItem)
        self.defaultField = QtWidgets.QTimeEdit(Time)
        self.defaultField.setMinimumSize(QtCore.QSize(200, 0))
        self.defaultField.setObjectName("defaultField")
        self.defaultLayout.addWidget(self.defaultField)
        self.verticalLayout.addLayout(self.defaultLayout)
        self.minValueLayout = QtWidgets.QHBoxLayout()
        self.minValueLayout.setObjectName("minValueLayout")
        self.minValueLabel = QtWidgets.QLabel(Time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minValueLabel.sizePolicy().hasHeightForWidth())
        self.minValueLabel.setSizePolicy(sizePolicy)
        self.minValueLabel.setObjectName("minValueLabel")
        self.minValueLayout.addWidget(self.minValueLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.minValueLayout.addItem(spacerItem1)
        self.minValueField = QtWidgets.QTimeEdit(Time)
        self.minValueField.setMinimumSize(QtCore.QSize(200, 0))
        self.minValueField.setObjectName("minValueField")
        self.minValueLayout.addWidget(self.minValueField)
        self.verticalLayout.addLayout(self.minValueLayout)
        self.maxValueLayout = QtWidgets.QHBoxLayout()
        self.maxValueLayout.setObjectName("maxValueLayout")
        self.maxValueLabel = QtWidgets.QLabel(Time)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxValueLabel.sizePolicy().hasHeightForWidth())
        self.maxValueLabel.setSizePolicy(sizePolicy)
        self.maxValueLabel.setObjectName("maxValueLabel")
        self.maxValueLayout.addWidget(self.maxValueLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.maxValueLayout.addItem(spacerItem2)
        self.maxValueField = QtWidgets.QTimeEdit(Time)
        self.maxValueField.setMinimumSize(QtCore.QSize(200, 0))
        self.maxValueField.setTime(QtCore.QTime(23, 59, 59))
        self.maxValueField.setObjectName("maxValueField")
        self.maxValueLayout.addWidget(self.maxValueField)
        self.verticalLayout.addLayout(self.maxValueLayout)
        self.increaseButtonsCheckbox = QtWidgets.QCheckBox(Time)
        self.increaseButtonsCheckbox.setChecked(True)
        self.increaseButtonsCheckbox.setObjectName("increaseButtonsCheckbox")
        self.verticalLayout.addWidget(self.increaseButtonsCheckbox)

        self.retranslateUi(Time)
        QtCore.QMetaObject.connectSlotsByName(Time)

    def retranslateUi(self, Time):
        _translate = QtCore.QCoreApplication.translate
        Time.setWindowTitle(_translate("Time", "Time"))
        self.defaultLabel.setText(_translate("Time", "Значение по умолчанию"))
        self.defaultField.setDisplayFormat(_translate("Time", "HH:mm:ss"))
        self.minValueLabel.setText(_translate("Time", "Минимальное значение"))
        self.minValueField.setDisplayFormat(_translate("Time", "HH:mm:ss"))
        self.maxValueLabel.setText(_translate("Time", "Максимальное значение"))
        self.maxValueField.setDisplayFormat(_translate("Time", "HH:mm:ss"))
        self.increaseButtonsCheckbox.setText(_translate("Time", "Кнопки увеличения даты"))
