# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/editor/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 165)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(475, 0))
        self.layout = QtWidgets.QVBoxLayout(Form)
        self.layout.setObjectName("layout")
        self.formLayout = QtWidgets.QHBoxLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelField = QtWidgets.QLineEdit(Form)
        self.labelField.setMinimumSize(QtCore.QSize(200, 0))
        self.labelField.setObjectName("labelField")
        self.formLayout.addWidget(self.labelField)
        self.typeEnum = QtWidgets.QComboBox(Form)
        self.typeEnum.setMinimumSize(QtCore.QSize(200, 0))
        self.typeEnum.setObjectName("typeEnum")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.typeEnum.addItem("")
        self.formLayout.addWidget(self.typeEnum)
        self.layout.addLayout(self.formLayout)
        self.propertiesLayout = QtWidgets.QVBoxLayout()
        self.propertiesLayout.setContentsMargins(0, 0, 0, 0)
        self.propertiesLayout.setSpacing(0)
        self.propertiesLayout.setObjectName("propertiesLayout")
        self.layout.addLayout(self.propertiesLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout.addItem(spacerItem)
        self.deleteButton = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon)
        self.deleteButton.setAutoDefault(False)
        self.deleteButton.setObjectName("deleteButton")
        self.layout.addWidget(self.deleteButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelField.setPlaceholderText(_translate("Form", "Название поля"))
        self.typeEnum.setItemText(0, _translate("Form", "Текст"))
        self.typeEnum.setItemText(1, _translate("Form", "Целое число"))
        self.typeEnum.setItemText(2, _translate("Form", "Рациональное число"))
        self.typeEnum.setItemText(3, _translate("Form", "Время"))
        self.typeEnum.setItemText(4, _translate("Form", "Дата"))
        self.typeEnum.setItemText(5, _translate("Form", "Дата и время"))
        self.typeEnum.setItemText(6, _translate("Form", "Флажок"))
        self.typeEnum.setItemText(7, _translate("Form", "Переключатель"))
        self.deleteButton.setText(_translate("Form", "Удалить"))
import src_rc
