# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/fields/checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Checkbox(object):
    def setupUi(self, Checkbox):
        Checkbox.setObjectName("Checkbox")
        Checkbox.resize(400, 48)
        Checkbox.setMinimumSize(QtCore.QSize(400, 0))
        Checkbox.setMaximumSize(QtCore.QSize(475, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Checkbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.field = QtWidgets.QCheckBox(Checkbox)
        self.field.setObjectName("field")
        self.horizontalLayout.addWidget(self.field)

        self.retranslateUi(Checkbox)
        QtCore.QMetaObject.connectSlotsByName(Checkbox)

    def retranslateUi(self, Checkbox):
        _translate = QtCore.QCoreApplication.translate
        Checkbox.setWindowTitle(_translate("Checkbox", "Checkbox"))
        self.field.setText(_translate("Checkbox", "Form label"))
