# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/fields/date.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Date(object):
    def setupUi(self, Date):
        Date.setObjectName("Date")
        Date.resize(400, 48)
        Date.setMinimumSize(QtCore.QSize(400, 0))
        Date.setMaximumSize(QtCore.QSize(475, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Date)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Date)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.field = QtWidgets.QDateEdit(Date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field.sizePolicy().hasHeightForWidth())
        self.field.setSizePolicy(sizePolicy)
        self.field.setObjectName("field")
        self.horizontalLayout.addWidget(self.field)

        self.retranslateUi(Date)
        QtCore.QMetaObject.connectSlotsByName(Date)

    def retranslateUi(self, Date):
        _translate = QtCore.QCoreApplication.translate
        Date.setWindowTitle(_translate("Date", "Date"))
        self.label.setText(_translate("Date", "Form label"))
