# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/fields/datetime.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Datetime(object):
    def setupUi(self, Datetime):
        Datetime.setObjectName("Datetime")
        Datetime.resize(400, 48)
        Datetime.setMinimumSize(QtCore.QSize(400, 0))
        Datetime.setMaximumSize(QtCore.QSize(475, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Datetime)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Datetime)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.field = QtWidgets.QDateTimeEdit(Datetime)
        self.field.setObjectName("field")
        self.horizontalLayout.addWidget(self.field)

        self.retranslateUi(Datetime)
        QtCore.QMetaObject.connectSlotsByName(Datetime)

    def retranslateUi(self, Datetime):
        _translate = QtCore.QCoreApplication.translate
        Datetime.setWindowTitle(_translate("Datetime", "Datetime"))
        self.label.setText(_translate("Datetime", "Form label"))
        self.field.setDisplayFormat(_translate("Datetime", "dd.MM.yyyy HH:mm:ss"))
