# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/fields/integer.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Integer(object):
    def setupUi(self, Integer):
        Integer.setObjectName("Integer")
        Integer.resize(400, 48)
        Integer.setMinimumSize(QtCore.QSize(400, 0))
        Integer.setMaximumSize(QtCore.QSize(475, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Integer)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Integer)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.field = QtWidgets.QSpinBox(Integer)
        self.field.setObjectName("field")
        self.horizontalLayout.addWidget(self.field)

        self.retranslateUi(Integer)
        QtCore.QMetaObject.connectSlotsByName(Integer)

    def retranslateUi(self, Integer):
        _translate = QtCore.QCoreApplication.translate
        Integer.setWindowTitle(_translate("Integer", "Integer"))
        self.label.setText(_translate("Integer", "Form label"))
