# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/fields/radio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Radio(object):
    def setupUi(self, Radio):
        Radio.setObjectName("Radio")
        Radio.resize(400, 38)
        Radio.setMinimumSize(QtCore.QSize(400, 0))
        Radio.setMaximumSize(QtCore.QSize(475, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Radio)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.field = QtWidgets.QRadioButton(Radio)
        self.field.setAutoExclusive(True)
        self.field.setObjectName("field")
        self.horizontalLayout.addWidget(self.field)

        self.retranslateUi(Radio)
        QtCore.QMetaObject.connectSlotsByName(Radio)

    def retranslateUi(self, Radio):
        _translate = QtCore.QCoreApplication.translate
        Radio.setWindowTitle(_translate("Radio", "Radio"))
        self.field.setText(_translate("Radio", "Form label"))
