# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/fields/text.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Text(object):
    def setupUi(self, Text):
        Text.setObjectName("Text")
        Text.resize(400, 48)
        Text.setMinimumSize(QtCore.QSize(400, 0))
        Text.setMaximumSize(QtCore.QSize(475, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Text)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Text)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.field = QtWidgets.QLineEdit(Text)
        self.field.setText("")
        self.field.setObjectName("field")
        self.horizontalLayout.addWidget(self.field)

        self.retranslateUi(Text)
        QtCore.QMetaObject.connectSlotsByName(Text)

    def retranslateUi(self, Text):
        _translate = QtCore.QCoreApplication.translate
        Text.setWindowTitle(_translate("Text", "Text"))
        self.label.setText(_translate("Text", "Form label"))
        self.field.setPlaceholderText(_translate("Text", "placeholder"))
