version: "3"

services:
  server:
    build: "."
    restart: "always"
    env_file:
      - env.env
    ports:
      - 5000:5000
  database:
    container_name: "pyquiz-database"
    image: postgres:bullseye
    restart: "always"
    env_file:
      - env.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
