# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Quiz(object):
    def setupUi(self, Quiz):
        Quiz.setObjectName("Quiz")
        Quiz.resize(500, 250)
        Quiz.setMinimumSize(QtCore.QSize(500, 250))
        Quiz.setMaximumSize(QtCore.QSize(16777215, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(Quiz)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.image = QtWidgets.QLabel(Quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(150, 150))
        self.image.setMaximumSize(QtCore.QSize(150, 150))
        self.image.setPixmap(QtGui.QPixmap(":/src/src/no-file.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.headerLayout.addWidget(self.image)
        self.label = QtWidgets.QLabel(Quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.headerLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.headerLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.startButton = QtWidgets.QPushButton(Quiz)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon)
        self.startButton.setAutoDefault(False)
        self.startButton.setObjectName("startButton")
        self.buttonsLayout.addWidget(self.startButton)
        self.editButton = QtWidgets.QPushButton(Quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/src/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editButton.setIcon(icon1)
        self.editButton.setAutoDefault(False)
        self.editButton.setObjectName("editButton")
        self.buttonsLayout.addWidget(self.editButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(Quiz)
        QtCore.QMetaObject.connectSlotsByName(Quiz)

    def retranslateUi(self, Quiz):
        _translate = QtCore.QCoreApplication.translate
        Quiz.setWindowTitle(_translate("Quiz", "Quiz"))
        self.label.setText(_translate("Quiz", "Quiz name"))
        self.startButton.setText(_translate("Quiz", "Пройти опрос"))
        self.editButton.setText(_translate("Quiz", "Изменить"))
import src_rc
