# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Quiz(object):
    def setupUi(self, Quiz):
        Quiz.setObjectName("Quiz")
        Quiz.resize(500, 208)
        Quiz.setMinimumSize(QtCore.QSize(500, 208))
        Quiz.setMaximumSize(QtCore.QSize(16777215, 208))
        self.verticalLayout = QtWidgets.QVBoxLayout(Quiz)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image = QtWidgets.QLabel(Quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(150, 150))
        self.image.setMaximumSize(QtCore.QSize(150, 150))
        self.image.setPixmap(QtGui.QPixmap(":/src/src/no-file.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.horizontalLayout_2.addWidget(self.image)
        self.label = QtWidgets.QLabel(Quiz)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(Quiz)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Quiz)
        QtCore.QMetaObject.connectSlotsByName(Quiz)

    def retranslateUi(self, Quiz):
        _translate = QtCore.QCoreApplication.translate
        Quiz.setWindowTitle(_translate("Quiz", "Quiz"))
        self.pushButton.setText(_translate("Quiz", "Открыть тест"))
import src_rc
