# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/dialogs/answers_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnswersView(object):
    def setupUi(self, AnswersView):
        AnswersView.setObjectName("AnswersView")
        AnswersView.resize(400, 700)
        AnswersView.setMinimumSize(QtCore.QSize(400, 700))
        AnswersView.setMaximumSize(QtCore.QSize(400, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(AnswersView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.answersArea = QtWidgets.QScrollArea(AnswersView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answersArea.sizePolicy().hasHeightForWidth())
        self.answersArea.setSizePolicy(sizePolicy)
        self.answersArea.setWidgetResizable(True)
        self.answersArea.setObjectName("answersArea")
        self.answersLayout = QtWidgets.QWidget()
        self.answersLayout.setGeometry(QtCore.QRect(0, 0, 384, 638))
        self.answersLayout.setObjectName("answersLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.answersLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.answersArea.setWidget(self.answersLayout)
        self.verticalLayout.addWidget(self.answersArea)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.cancelButton = QtWidgets.QPushButton(AnswersView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.exportButton = QtWidgets.QPushButton(AnswersView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/src/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportButton.setIcon(icon1)
        self.exportButton.setAutoDefault(False)
        self.exportButton.setObjectName("exportButton")
        self.buttonsLayout.addWidget(self.exportButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(AnswersView)
        self.cancelButton.clicked.connect(AnswersView.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AnswersView)

    def retranslateUi(self, AnswersView):
        _translate = QtCore.QCoreApplication.translate
        AnswersView.setWindowTitle(_translate("AnswersView", "Answers view"))
        self.cancelButton.setText(_translate("AnswersView", "Отменить"))
        self.exportButton.setText(_translate("AnswersView", "Экспорт"))
import src_rc
