# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/dialogs/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(400, 300)
        AuthDialog.setMinimumSize(QtCore.QSize(400, 300))
        AuthDialog.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.authTabWidget = QtWidgets.QTabWidget(AuthDialog)
        self.authTabWidget.setObjectName("authTabWidget")
        self.loginLayout = QtWidgets.QWidget()
        self.loginLayout.setObjectName("loginLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginUsernameField = QtWidgets.QLineEdit(self.loginLayout)
        self.loginUsernameField.setObjectName("loginUsernameField")
        self.verticalLayout_2.addWidget(self.loginUsernameField)
        self.loginPasswordField = QtWidgets.QLineEdit(self.loginLayout)
        self.loginPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPasswordField.setObjectName("loginPasswordField")
        self.verticalLayout_2.addWidget(self.loginPasswordField)
        self.loginShowPasswordCheckbox = QtWidgets.QCheckBox(self.loginLayout)
        self.loginShowPasswordCheckbox.setObjectName("loginShowPasswordCheckbox")
        self.verticalLayout_2.addWidget(self.loginShowPasswordCheckbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.loginButton = QtWidgets.QPushButton(self.loginLayout)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon)
        self.loginButton.setAutoDefault(False)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_2.addWidget(self.loginButton)
        self.authTabWidget.addTab(self.loginLayout, "")
        self.registerLayout = QtWidgets.QWidget()
        self.registerLayout.setObjectName("registerLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.registerLayout)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.registerUsernameField = QtWidgets.QLineEdit(self.registerLayout)
        self.registerUsernameField.setObjectName("registerUsernameField")
        self.verticalLayout_3.addWidget(self.registerUsernameField)
        self.registerPasswordField = QtWidgets.QLineEdit(self.registerLayout)
        self.registerPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerPasswordField.setObjectName("registerPasswordField")
        self.verticalLayout_3.addWidget(self.registerPasswordField)
        self.registerRepeatPasswordField = QtWidgets.QLineEdit(self.registerLayout)
        self.registerRepeatPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.registerRepeatPasswordField.setObjectName("registerRepeatPasswordField")
        self.verticalLayout_3.addWidget(self.registerRepeatPasswordField)
        self.registerShowPasswordCheckbox = QtWidgets.QCheckBox(self.registerLayout)
        self.registerShowPasswordCheckbox.setObjectName("registerShowPasswordCheckbox")
        self.verticalLayout_3.addWidget(self.registerShowPasswordCheckbox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.registerButton = QtWidgets.QPushButton(self.registerLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/src/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerButton.setIcon(icon1)
        self.registerButton.setAutoDefault(False)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout_3.addWidget(self.registerButton)
        self.authTabWidget.addTab(self.registerLayout, "")
        self.verticalLayout.addWidget(self.authTabWidget)

        self.retranslateUi(AuthDialog)
        self.authTabWidget.setCurrentIndex(1)
        self.loginUsernameField.returnPressed.connect(self.loginPasswordField.setFocus) # type: ignore
        self.registerUsernameField.returnPressed.connect(self.registerPasswordField.setFocus) # type: ignore
        self.registerPasswordField.returnPressed.connect(self.registerRepeatPasswordField.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Auth"))
        self.loginUsernameField.setPlaceholderText(_translate("AuthDialog", "Логин"))
        self.loginPasswordField.setPlaceholderText(_translate("AuthDialog", "Пароль"))
        self.loginShowPasswordCheckbox.setText(_translate("AuthDialog", "Показать пароль"))
        self.loginButton.setText(_translate("AuthDialog", "Войти"))
        self.authTabWidget.setTabText(self.authTabWidget.indexOf(self.loginLayout), _translate("AuthDialog", "Вход"))
        self.registerUsernameField.setPlaceholderText(_translate("AuthDialog", "Логин"))
        self.registerPasswordField.setPlaceholderText(_translate("AuthDialog", "Пароль"))
        self.registerRepeatPasswordField.setPlaceholderText(_translate("AuthDialog", "Повторите пароль"))
        self.registerShowPasswordCheckbox.setText(_translate("AuthDialog", "Показать пароль"))
        self.registerButton.setText(_translate("AuthDialog", "Зарегистрироваться"))
        self.authTabWidget.setTabText(self.authTabWidget.indexOf(self.registerLayout), _translate("AuthDialog", "Регистрация"))
import src_rc
