# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/dialogs/editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuizEditor(object):
    def setupUi(self, QuizEditor):
        QuizEditor.setObjectName("QuizEditor")
        QuizEditor.resize(555, 516)

        self.retranslateUi(QuizEditor)
        QtCore.QMetaObject.connectSlotsByName(QuizEditor)

    def retranslateUi(self, QuizEditor):
        _translate = QtCore.QCoreApplication.translate
        QuizEditor.setWindowTitle(_translate("QuizEditor", "Editor"))
