# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/dialogs/editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuizEditor(object):
    def setupUi(self, QuizEditor):
        QuizEditor.setObjectName("QuizEditor")
        QuizEditor.resize(600, 850)
        QuizEditor.setMinimumSize(QtCore.QSize(600, 850))
        QuizEditor.setMaximumSize(QtCore.QSize(600, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(QuizEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.quizLayout = QtWidgets.QHBoxLayout()
        self.quizLayout.setObjectName("quizLayout")
        self.image = QtWidgets.QLabel(QuizEditor)
        self.image.setMinimumSize(QtCore.QSize(150, 150))
        self.image.setMaximumSize(QtCore.QSize(150, 150))
        self.image.setPixmap(QtGui.QPixmap(":/src/src/no-file.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.quizLayout.addWidget(self.image)
        self.labelField = QtWidgets.QLineEdit(QuizEditor)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelField.setFont(font)
        self.labelField.setFrame(True)
        self.labelField.setObjectName("labelField")
        self.quizLayout.addWidget(self.labelField)
        self.verticalLayout.addLayout(self.quizLayout)
        self.imageURLField = QtWidgets.QLineEdit(QuizEditor)
        self.imageURLField.setMinimumSize(QtCore.QSize(150, 0))
        self.imageURLField.setClearButtonEnabled(True)
        self.imageURLField.setObjectName("imageURLField")
        self.verticalLayout.addWidget(self.imageURLField)
        self.addFieldButton = QtWidgets.QPushButton(QuizEditor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/src/src/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFieldButton.setIcon(icon)
        self.addFieldButton.setAutoDefault(False)
        self.addFieldButton.setObjectName("addFieldButton")
        self.verticalLayout.addWidget(self.addFieldButton)
        self.questionTabs = QtWidgets.QTabWidget(QuizEditor)
        self.questionTabs.setMovable(True)
        self.questionTabs.setObjectName("questionTabs")
        self.verticalLayout.addWidget(self.questionTabs)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        self.deleteButton = QtWidgets.QPushButton(QuizEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/src/src/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon1)
        self.deleteButton.setAutoDefault(False)
        self.deleteButton.setObjectName("deleteButton")
        self.buttonsLayout.addWidget(self.deleteButton)
        self.cancelButton = QtWidgets.QPushButton(QuizEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/src/src/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon2)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonsLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(QuizEditor)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/src/src/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon3)
        self.saveButton.setAutoDefault(False)
        self.saveButton.setObjectName("saveButton")
        self.buttonsLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(QuizEditor)
        QtCore.QMetaObject.connectSlotsByName(QuizEditor)

    def retranslateUi(self, QuizEditor):
        _translate = QtCore.QCoreApplication.translate
        QuizEditor.setWindowTitle(_translate("QuizEditor", "Editor"))
        self.labelField.setPlaceholderText(_translate("QuizEditor", "Название опроса"))
        self.imageURLField.setPlaceholderText(_translate("QuizEditor", "Ссылка на изображение"))
        self.addFieldButton.setText(_translate("QuizEditor", "Добавить вопрос"))
        self.deleteButton.setText(_translate("QuizEditor", "Удалить"))
        self.cancelButton.setText(_translate("QuizEditor", "Отменить"))
        self.saveButton.setText(_translate("QuizEditor", "Сохранить"))
import src_rc
