# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/widgets/answer/question.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Question(object):
    def setupUi(self, Question):
        Question.setObjectName("Question")
        Question.resize(475, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Question.sizePolicy().hasHeightForWidth())
        Question.setSizePolicy(sizePolicy)
        Question.setMinimumSize(QtCore.QSize(475, 100))
        Question.setMaximumSize(QtCore.QSize(475, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Question)
        self.verticalLayout.setObjectName("verticalLayout")
        self.questionBox = QtWidgets.QGroupBox(Question)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.questionBox.sizePolicy().hasHeightForWidth())
        self.questionBox.setSizePolicy(sizePolicy)
        self.questionBox.setObjectName("questionBox")
        self.fieldsLayout = QtWidgets.QVBoxLayout(self.questionBox)
        self.fieldsLayout.setObjectName("fieldsLayout")
        self.verticalLayout.addWidget(self.questionBox)

        self.retranslateUi(Question)
        QtCore.QMetaObject.connectSlotsByName(Question)

    def retranslateUi(self, Question):
        _translate = QtCore.QCoreApplication.translate
        Question.setWindowTitle(_translate("Question", "Question"))
        self.questionBox.setTitle(_translate("Question", "Question name"))
